version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8082:8082"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
